### ISSUE TITLE
AttributeError: module 'testlink' has no attribute 'TestLinkHelper'

### ISSUE THREAD

**Issue by ashakn-murthy** [Beanking77/Robot-Framework-Report-update-to-Testlink#2]
Hi, 

I used your updater.py file to integrate with my Robot Framework output.xml file parsing. I get the following error .

I am using Python3 version. I edited the xmlrpclib to xmlrpc.client as it was giving error for Python 3 .

python Updater.py -p "TestProject" -t "TestPlan1" -f "Chrome" -b "Build1" --file output.xml
Traceback (most recent call last):
  File "Updater.py", line 183, in <module>
    testlink_feeder = TestlinkFeeder(args.project, args.testplan, args.platform, args.build)
  File "Updater.py", line 128, in __init__
    self.robotI = RobotI()
  File "Updater.py", line 18, in __init__
    tl_helper = testlink.TestLinkHelper()
AttributeError: module 'testlink' has no attribute 'TestLinkHelper'

**Comment by Beanking77** [comment]
Hi @ashakn-murthy,

Sorry for really late reply. It's been a while not maintaining this tool.
But I'm try to  run following command:
```
OS: Ubuntu 20.04.2 LTS

$ apt update && apt install python3
$ apt-get install python3-pip
$ pip3 install TestLink-API-Python-client
$ python3
>>> import testlink
>>> tl_helper = testlink.TestLinkHelper()
>>> testlinker = tl_helper.connect(testlink.TestlinkAPIClient)
```
Seems fine, though I not sure are those library were still support python3 or not.
